/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'pitch-darkness': '#100904',
        'cork-dust': '#ffedd7',
        'rust-accent': '#dc5000',
        'olive-green': '#445231',
        'faded-bark': '#382416',
        'aged-stone': '#887b6d',
        'light-cork': '#f6e0c6',
        'faint-hazel': '#bbac97',
        'subtle-moss': '#5d6c49',
        'grayscale-gray': '#808080',
        'chalkboard-black': '#000000',
        'deep-mocha': '#40372e',
      },
      fontFamily: {
        'halyard': 'var(--font-halyard), ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        'literata': 'var(--font-literata), ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        'mono': 'var(--font-mono), ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace',
      },
      fontSize: {
        'xs': ['10px', { lineHeight: '1.5' }],
        'sm': ['12px', { lineHeight: '1.33' }],
        'base': ['14px', { lineHeight: '1.33' }],
        'lg': ['16px', { lineHeight: '1.26' }],
        'xl': ['18px', { lineHeight: '1.2' }],
        '2xl': ['23px', { lineHeight: '1.09', letterSpacing: '-0.018px' }],
        '3xl': ['34px', { lineHeight: '1.09', letterSpacing: '-0.018px' }],
        '4xl': ['49px', { lineHeight: '1', letterSpacing: '-0.018px' }],
        '5xl': ['64px', { lineHeight: '0.9', letterSpacing: '-0.045px' }],
        '6xl': ['147px', { lineHeight: '0.9', letterSpacing: '-0.045px' }],
        '7xl': ['410px', { lineHeight: '0.9', letterSpacing: '-0.045px' }],
      },
      spacing: {
        '6': '6px',
        '9': '9px',
        '11': '11px',
        '12': '12px',
        '14': '14px',
        '15': '15px',
        '16': '16px',
        '18': '18px',
        '20': '20px',
        '23': '23px',
        '24': '24px',
        '34': '34px',
        '36': '36px',
        '45': '45px',
        '77': '77px',
        '86': '86px',
      },
      borderRadius: {
        'xl': '12px',
        '2xl': '22.5px',
        '3xl': '36px',
      },
      backgroundImage: {
        'gradient-rainbow': 'linear-gradient(to right, rgb(253, 254, 237), rgb(255, 191, 2) 17%, rgb(233, 80, 14) 32%, rgb(205, 25, 125), rgb(140, 1, 156), rgb(37, 1, 135), rgb(3, 3, 16))',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        fadeInRight: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInUp: {
          '0%': { transform: 'translateY(40px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        glow: {
          '0%, 100%': { boxShadow: '0 0 5px rgba(220, 80, 0, 0.2)' },
          '50%': { boxShadow: '0 0 20px rgba(220, 80, 0, 0.4)' },
        },
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'fadeInUp': 'fadeInUp 0.6s ease-out',
        'fadeInLeft': 'fadeInLeft 0.6s ease-out',
        'fadeInRight': 'fadeInRight 0.6s ease-out',
        'slideInUp': 'slideInUp 0.6s ease-out',
        'glow': 'glow 3s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
